### ISSUE TITLE
Why not using GIR

### ISSUE THREAD

**Issue by gavr123456789** [can-lehmann/owlkettle#1]
https://gi.readthedocs.io/en/latest/  
Now GTK applications are being ported to GTK 4 and LibAdwaita  
https://release.gnome.org/42/  -> Upgraded Apps  
Also what do you think about gintro project?

**Comment by can-lehmann** [comment]
**GObject Introspection**

I looked at using GIR for creating owlkettle, but eventually decided against using it for multiple reasons.

Owlkettle **is not** simply another GTK binding. In fact less than 400 lines of code (out of 2348 lines for the complete owlkettle library) are part of owlkettle's custom GTK binding. When using GIR, all hooks used to update widgets would have to be generated automatically (otherwise what is the point of using GIR in the first place). This might be feasible for simple properties (such as the text of a label), but will get extremly difficult once a bit more logic is required. Especially hooks which update the children of a widget can get quite complex (see https://github.com/can-lehmann/owlkettle/blob/main/owlkettle/widgets.nim#L217 for example).

**GTK4**

Initially owlkettle targeted GTK4, but I quickly encountered the [blurry text issue](https://gitlab.gnome.org/GNOME/gtk/-/issues/3787), which was a deal breaker for me. The GTK4 version that shipped with Fedora at the time was also not current enough to support the suggested workaround. I do however definitely plan to switch to GTK4 once this issue has been resolved, or an acceptable workaround is found. 

**Gintro**

I used gintro in the past, and found it quite nice to work with. However, it obviously does not support building GUIs declarativly (and no, `GtkBuilder` is not proper declarative ui imo).

I also decided to create custom GTK bindings for owlkettle, since I always found gintros compile times to be quite slow. This is understandable, since gintro provides many convenient ways to call methods, set properties, etc., but since owlkettle does not expose any of the underlying GTK interface to the user, I do not think that the increased compilation time is justified by me having a tiny bit less work.

**Comment by gavr123456789** [comment]
> However, it obviously does not support building GUIs declarativly  
  
Yes, but this does not mean that macros representing a declarative UI cannot be made on its basis. But anyway gintro need big refactor, it was written on string macros thats really hard to undestand and maintain.   
  
The thing with GIR is - there are too many userfull GIR packages for example, what if I need to use SourceView. Second reason is that you don't need to manually rewrite bindings after updating packages(LibAdwaita is being updated quite often now).

**Comment by can-lehmann** [comment]
> Yes, but this does not mean that macros representing a declarative UI cannot be made on its basis.

You are correct, I could have used gintro as a basis for owlkettle. I decided against doing so because of the aforementioned longer compile times.

> The thing with GIR is - there are too many userfull GIR packages for example, what if I need to use SourceView

Currently, you would have to create bindings for these packages on your own. This is quite easy in most cases, since the `renderable` macro helps you in doing so, but can also get very tricky once a widget has child widgets. The second (difficult) case is also the reason for why generating owlkettle widgets from GIR is not easily possible.
