### ISSUE TITLE
Temperature converter ex: negative values

### ISSUE THREAD

**Issue by dlesnoff** [can-lehmann/owlkettle#21]
Just tested some examples for the first time today.
There is a funny thing about the temperature converter : it accepts mathematical expressions (-,+,*,/ but probably not ^ unless imported with std/math).

Yet, it does not accept any negative number in the celsius field at least.
But it converts without problem if 0.0-1.0 is given.

As a side not too, "1.0/" in the Celsius Field gives "inf" in the Farenheit field while I suppose it should tell it is an invalid value instead.

These are not really bug/limitations of the owlkettle library, but of the demo itself.
Feel free to close this "issue", since I guess bugs in the library are more important than bugs in the demos.

**Comment by can-lehmann** [comment]
Thank you for the report! This is actually a bug in owlkettle, since the `dataentries` module which provides the `FormulaEntry` widget implements its own parser. I (hopefully) fixed parsing negative numbers in https://github.com/can-lehmann/owlkettle/commit/a7c9cc4ccef5a9e458459ceecefa87a87a9d92b9.

I am unable to reproduce the "1.0/" bug.
