### ISSUE TITLE
Support for libwebkit2gtk?

### ISSUE THREAD

**Issue by georgelemon** [can-lehmann/owlkettle#24]
Sexy macros! Any plans to implement libwebkit2gtk? That would be hot

**Comment by can-lehmann** [comment]
I remember someone asking for webkitgtk support some time ago on the Nim Discord. Back then Fedora did not include a webkitgtk version that was compatible with GTK4. At the time I did not want to compile a compatible version of webkitgtk from scratch, so the project was abandoned. In the meantime Fedora added the `webkit2gtk5.0-devel` package which is compatible with GTK4. I still had the code laying around, and it turns out that it just works:

Here is the `owlkettle_webkit` module which wraps the WebView widget:

```nim
import owlkettle, owlkettle/[gtk]

{.passl: gorge("pkg-config --libs webkit2gtk-5.0").}

{.push importc.}
proc webkit_web_view_new(): GtkWidget
proc webkit_web_view_load_uri(webView: GtkWidget, uri: cstring)
{.pop.}

renderable WebView:
  uri: string
  
  hooks:
    beforeBuild:
      state.internalWidget = webkit_web_view_new()
  
  hooks uri:
    property:
      webkit_web_view_load_uri(state.internalWidget, state.uri)

export WebView
```

And here is a simple example Browser Application that uses this widget.

```nim
import owlkettle, owlkettle/adw
import owlkettle_webkit

viewable App:
  search: string = "https://www.example.com"
  uri: string = "https://www.example.com"

method view(app: AppState): Widget =
  result = gui:
    Window:
      title = "Owlkettle Webkit Browser"
      
      HeaderBar {.addTitlebar.}:
        Entry {.addTitle.}:
          text = app.search
          
          proc changed(text: string) =
            app.search = text
          
          proc activate() =
            app.uri = app.search
      
      WebView:
        uri = app.uri

adw.brew(gui(App()))
```

**Comment by can-lehmann** [comment]
Of course this is just a proof of concept which cannot (and should not) be used for implementing anything complex. The main issue with wrapping webkitgtk is designing an API for webkitgtk which is declartive. Webkitgtk heavily relies on sending messages to the WebView widget (reload, load_uri, go_back, ...) , which is not possible in a declarative framework like owlkettle.

**Comment by can-lehmann** [comment]
I currently do not want to add a WebView widget to owlkette directly, since I dont want to have webkitgtk as a dependency for owlkettle (most users probably wont need webkitgtk). Maybe this could be a separate module/extension.
