### ISSUE TITLE
Add mention of gtk4-icon-browser for figuring out available icons to docs

### ISSUE THREAD

**Issue by PhilippMDoerner** [can-lehmann/owlkettle#26]
First up, thanks for making the library! I'm new to GUI toolkits like GTK/QT (originally webdev) and I've been playing around with this for a couple hours and had quite a bit of fun with how quickly and easily everything fit together, particularly how easy it was to split Widgets into their own files and have them share data!

I was fiddling around with the todo-list tutorial and I noticed it using a couple icons here or there. That got me wondering what the available icons were. After 15 minutes of googling and some luck I stumbled over a mention of gtk4-icon-browser. A bit of more googling later on how to install that and I had a chance to see what icons there are. It would be nice if we could shorten that link from "Oh, what icons can I have?" to finding that list for newcomers such as myself.

Imo it makes sense to  mention in the docs what tooling there is out there that one likely needs, such as gtk4-icon-browser to see a list of available icons. If there are more things out there that one should know about I'd love to of course also know about those ^^ 

I'd be happy to write a 3-4 line paragraph for this, but I'm not sure where this should be mentioned. A separate "recommended-tools.md" ? As part of "widgets.md" at the bottom?

**Comment by can-lehmann** [comment]
Thanks for trying owlkettle! Its always great to get feedback on the library.

I personally use [IconLibrary](https://apps.gnome.org/app/org.gnome.design.IconLibrary) for finding icons and [Color Palette](https://apps.gnome.org/app/org.gnome.design.Palette/) for referencing the GNOME color scheme. Other [GNOME Design tools](https://tools.design.gnome.org) might also be useful. When wrapping new widgets, [Devhelp](https://apps.gnome.org/app/org.gnome.Devhelp/) might be useful for reading GTK documentation.

I agree that this should be documented somewhere. I think that adding a note next to the docs for `Icon.name` in [widgets.md](https://github.com/can-lehmann/owlkettle/blob/main/docs/widgets.md#icon) would be ideal. This is currently not possible though since `widgets.md` is automatically generated from the owlkette source code and the generator does not support adding notes/comments.

A `recommended-tools.md` seems like a good idea, since it would provide a central place for documenting some of the tools which are used when developing owlkettle applications.

**Comment by PhilippMDoerner** [comment]
Actually, question regarding Devhelp, have you actually managed to find it useful so far? As part of #28 I tried to search for the meaning of SelectionMode,even when knowing that the individual enum values were GTK_SELECTION_* I didn't manage to find the docs properly. Is there some kind of trick to it.

**Comment by can-lehmann** [comment]
I use Devhelp sometimes when wrapping widgets. The search works quite well for me. When I search for `GTK_SELECTION_`, the correct enum is shown as expected:

![image](https://user-images.githubusercontent.com/85876381/217077663-e8371779-4016-4650-a8f7-2c3d2b46f310.png)

Maybe there is a configuration issue somewhere. Does your Devhelp installation show a list of installed documentation files in the sidebar when you open it initially?

![image](https://user-images.githubusercontent.com/85876381/217079132-cf4cacb4-e236-4157-a4ad-cd29b3402e8c.png)

**Comment by PhilippMDoerner** [comment]
It does:
![image](https://user-images.githubusercontent.com/65814317/217079604-604742d8-7e20-42bb-a943-c30f8b10afa7.png)

But apparently not the one needed (I did install it via flatpak):

![Uploading image.png…]()

**Comment by can-lehmann** [comment]
It looks like the Gtk manuals are missing. I installed it through Fedoras dnf repos, which works quite well. On Fedora, there are specific documentation packages (such as `gtk4-devel-docs`) which presumably contain the docs. I have not tried the Flatpak version so far.

![image](https://user-images.githubusercontent.com/85876381/217083051-cd1896ac-9fb5-4938-b955-6b4241855f77.png)

**Comment by PhilippMDoerner** [comment]
Thanks for that name-drop! It took a bit of search until on arch I found `gtk4-docs-1:4.8.3-3`, installing that did the trick.
Given that I'll add a "documentation" section that denotes how to access those things.

On that note, good idea to keep the Symbols similar to the GTK ones, makes searching really simple!
