### ISSUE TITLE
Add links to gtk docs for enums (or other things where that might be useful)

### ISSUE THREAD

**Issue by PhilippMDoerner** [can-lehmann/owlkettle#28]
Heyho!
Similar to #26 I stumbled over something that I thought might facilitate "finding" something. I wanted to select a "SelectionMode" for ListBox and had no idea what `SelectionBrowse` was and couldn't differentiate it at a glance from `SelectionSingle`.

On the assumption that this was gtk stuff with a bit of googling and clicking around the ListBox docs I finally found https://docs.gtk.org/gtk4/enum.SelectionMode.html . I think it could make sense to add these links to the Widget documentation. Similarly as per #26 I'd be happy to do a PR to add those as I stumble over them, assuming that is desired.

**Comment by PhilippMDoerner** [comment]
Even though we already have a mention of DevHelp, which should help here, I think this would still be a good idea, because it's not Immediately obvious das `SelectionSingle` translates to `GTK_SELECTION_SINGLE`. Though given with the mention of Devhelper, that's not that strong of an rgument imo.

I'd still be happy to throw the links together though, would that have your approval @can-lehmann  ?

**Comment by PhilippMDoerner** [comment]
Ohhhhhhhhhh sick!

This is unrelated to the current issue, but I was playing with the thought of adding docs to the widget that give like a short one-liner for the intended usecase of each Widget and what ability make them "stand out". That idea came around when I was staring at Box, ListBox, Paned etc. to make a sidebar. So if doc-comments are supported now that could be a nice thing to have!

**Comment by can-lehmann** [comment]
Definitely! I already started doing that a bit for some widgets, but it is of course far from finished. Any help would be welcome :)

**Comment by can-lehmann** [comment]
IANAL, but just copying comments from the GTK repo would be problematic though, since it is licensed under LGPL. So it is somewhat important to write these comments specifically for owlkettle. Besides the legal aspect, this will hopefully also result in better documentation, since the GTK docs do not apply fully to owlkettle.

**Comment by PhilippMDoerner** [comment]
Okay, we achieved quite a lot for this ticket.
Since we now have nimibook docs, I'd float the idea to transform the tutorial to a nimibook in order to also have it checked whenever owlkettle changes.
I'd also include the example in the Readme but I don't know how to manage that one.

**Comment by can-lehmann** [comment]
Not sure if it is possible to convert the tutorial to a nimib document, since it mostly shows "code diffs" (though it would be pretty nice to find a better, more readable solution for those; e.g. allowing you to expand them / make an animated code editor that gets added to with each step). 
I think we would have to split the README into two files, the md for GitHub and a nimib file. I think nimib has a markdown backend, so you could potentially generate the GitHub Markdown file from the nimib file.

**Comment by PhilippMDoerner** [comment]
I'd argue we can close the issue and I just forgot to do so, because we now have a nimibook and I see over the months it even got some further work done on it!

**Comment by can-lehmann** [comment]
I agree. Thanks again for all the work you put into the docs! :smile:
