### ISSUE TITLE
[FR] enable github discussions feature

### ISSUE THREAD

**Issue by ITwrx** [can-lehmann/owlkettle#44]
hi,
any chance you might enable github's Discussions feature for this repo, so people can ask questions for general support and/or to clarify things prior to creating an issue report? It would probably cut down on invalid bug reports, questions in the issue tracker, and help new users get started. Users could eventually help each other, and save owlkettle devs some time, etc. 

I'm not in favor of projects using ephemeral chat for support because the same questions get asked and answered over and over again, and i don't like bothering people with something basic that has already been asked and could have been documented by forum software. 

thanks

**Comment by can-lehmann** [comment]
Good idea. I think it should be enabled now. I also think that having an official channel for asking & answering questions that also allows searching the existing answers is quite useful. It might currently take some time for me to respond though  (same goes for issues as well), since I am currently quite busy irl.

**Comment by ITwrx** [comment]
> Good idea. I think it should be enabled now. I also think that having an official channel for asking & answering questions that also allows searching the existing answers is quite useful.

great!

> It might currently take some time for me to respond though (same goes for issues as well), since I am currently quite busy irl.

understood. thanks for the warning. :)
