### ISSUE TITLE
Counter example wasn't compile

### ISSUE THREAD

**Issue by milustreamer** [can-lehmann/owlkettle#52]
When I try to run/compile the counter example on the start page with "nimble run", then comes the error "Error: type mismatch: got 'array[0..0, ButtonStyle]' for '[ButtonSuggested]' but expected 'set[ButtonStyle]' ".
The error relates to source line "style = [ButtonSuggested]", when I changed it to "style = {ButtonSuggested}" it compiled and run.

I used owl kettle on Apple M1 Ultra Ventura 13.3

**Comment by milustreamer** [comment]
I have forgot about the Version from him it is 1.6.12.

**Comment by can-lehmann** [comment]
The `main` branch in this repository is the development version of owlkettle. We changed the syntax for styling since the latest release, that is why the examples do not work.

You have two options:

1) You can install the development version of owlkettle using `nimble install owlkettle@#head`. I would recommend this method, since it also allows you to use the new development docs: https://can-lehmann.github.io/owlkettle/README
2) You can use the examples from version 2.2.0. I think the easiest way to get them is downloading the archive here: https://github.com/can-lehmann/owlkettle/releases/tag/v2.2.0

**Comment by can-lehmann** [comment]
I think it might be worth having a dedicated `devel` branch in the future, in order to avoid confusion. I will leave this issue open for now, as a reminder for myself to create such a branch.

**Comment by milustreamer** [comment]
I have used the development path as you said and all looks good. Thank you for the fine library.
