### ISSUE TITLE
Add `Expander` widget

### ISSUE THREAD

**Issue by can-lehmann** [can-lehmann/owlkettle#85]
https://docs.gtk.org/gtk4/class.Expander.html

**Comment by PhilippMDoerner** [comment]
I've started working on this and would call it mostly done.

For the most part I'd wait with a PR to see the outcome of the autoForm PR in order to adjust based on whatever that outcome is.

Other than that, [my branch](https://github.com/can-lehmann/owlkettle/compare/main...PhilippMDoerner:owlkettle:%2385-add-expander) contains the following:
- Fully wrapped Widget, including bindings for the activate signal
- expander.nim example
- 200% Screenshot of expander.nim example and updated examples/README.md
- Updated widgets.md as per `nimble genDocs`
