### ISSUE TITLE
Add `Video` widget

### ISSUE THREAD

**Issue by can-lehmann** [can-lehmann/owlkettle#87]
https://docs.gtk.org/gtk4/class.Video.html

This also requires creating a wrapper for `MediaStream` and `MediaFile`.

**Comment by PhilippMDoerner** [comment]
> This also requires creating a wrapper for MediaStream and MediaFile.
Does it?
I've been playing around here and getting video to play is easy enough just by the filename.
The main problem that does pose is that it leaks memory like a sieve and I'm not yet sure what needs to be freed via `g_object_unref` as it seemingly isn't the MediaStream (at least that doesn't fix the leak).

**Comment by can-lehmann** [comment]
> Does it?
>  I've been playing around here and getting video to play is easy enough just by the filename.

While technically true, the "requires" here is a requirement for the API from my side. I think library users should be able to have an API to pause, seek, mute, play, ... a video so that they can implement their own controls. If `filename` is implemented at all, it should just be a setter for the `mediaStream` field. This is actually [also what GTK does internally](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkvideo.c#L721), so `set_filename` is basically also just a setter for them, not actually a property on the widget.

**Comment by PhilippMDoerner** [comment]
This is a sanity check for myself:
Video holds a pointer to a file that it streams the contents of.
That file needs to be closed in order to avoid memory leaks when the Video widget is destroyed, correct?

Therefore, I will have to add an eventCallback for `destroy` of `GtkWidget` so that I can call `g_object_unref` on GtkMediaStream when the Video widget gets destroyed.

Does that sound correct so far?

If so, could it make sense to turn expand upon that a little and introduce a `destroy` hook whose execution gets triggered by the [`Widget::destroy`](https://docs.gtk.org/gtk4/signal.Widget.destroy.html) signal? I mean, Video is unlikely the only Widget ever that'll exist where the Widget grabs resources that should be free'd upon destruction of the Widget.

**Comment by PhilippMDoerner** [comment]
And thus this issue can be closed :smile:

**Comment by can-lehmann** [comment]
Yes
